### ISSUE TITLE
has no method forEach

### ISSUE THREAD

**Issue by iDVB** [webpack/extract-text-webpack-plugin#100]
I learned the heard way that you have to be careful with the key name of `loaders`.

I was following this tut http://goo.gl/tfVK4L and forgot to change the key `loaders` to `loader` once I implemented `extract-text-webpack-plugin`

``` javascript
            { // SASS & CSS FILES
                test: /\.scss$/,
                loader: ExtractTextPlugin.extract('css!sass')
            }
```

pay specific attention to..  
**loader**: ExtractTextPlugin.extract('css!sass')
and not
loader**s**: ExtractTextPlugin.extract('css!sass')

**Comment by abhinavsingi** [comment]
I'm using webpack-2 and using `use`, I'm still getting this error.
part of the config:
```{
        test: /\.scss$/,
        exclude: [
          /node_modules/,
          /\.mod\.scss$/,
        ],
        use: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: [
            'dynamic-style-loader',
            {
              loader: 'css-loader',
              options: CSS_LOADER_OPTIONS,
            },
            {
              loader: 'postcss-loader',
              options: POSTCSS_LOADER_OPTIONS,
            },
            {
              loader: 'sass-loader',
              options: SASS_LOADER_OPTIONS,
            },
          ],
        }),
      },```

**Comment by evilebottnawi** [comment]
@iDVB `dynamic-style-loader` and `style-loader` seems weird

**Comment by evilebottnawi** [comment]
@iDVB `options.fallback` - `{String}/{Array}/{Object}`.Try to using `fallback: ['style-loader', 'dynamic-style-loader']`
