### ISSUE TITLE
Not providing css modules

### ISSUE THREAD

**Issue by blainekasten** [webpack/extract-text-webpack-plugin#111]
So, my setup here is pretty complex and I'll try to walk through all of it, but effectively, this is my issue that my compiled file's `style` package looks like this:

```js
/***/ 975:
/*!*********************************************************************!*\
  !*** ../~/hudl-video-interface/src/Video/ContextProvider/style.css ***!
  \*********************************************************************/
/***/ function(module, exports) {

	// removed by extract-text-webpack-plugin

/***/ },
```

Where as I expect it to look something like this:

```js
/* 166 */
/***/ function(module, exports) {

	// removed by extract-text-webpack-plugin
	module.exports = {"wrapper":"_3XJAPiyzGGnTqFTAXQsp69","videodev":"kls0OG1mJ6ts6aodKOJTR","videoHolder":"_1SO5-_Ier8TVYrMzqJNNWa"};

/***/ },
```

So, to explain my setup. Effectively, I'm loading in a project through npm that uses es6 and local css through webpack. So my folder structure will be something like this:

```
  build/

  source/
    app/
      index.js

  node_modules/
    hudl-external_project/
      index.js
      style.css
```

My webpack config file is setup to parse through those files:

```js
  var cssLoader = [{
    extensions: ['css'],
    test: /\.css$/,
    loader: ExtractTextPlugin.extract('style-loader', 'css-loader'),
    include: matchFiles('node_modules/hudl-*/', source).concat(
      path.join(source, 'app')
    ),
  }]
```

`matchFiles` essentially returns an array of absolute filepaths for that glob.

So it should be running the `ExtractTextPlugin` on those files and putting in the local modules. Any guidance would be appreciated

**Comment by blainekasten** [comment]
So. I found out that I was using an old version of css-loader when the syntax was different. Closing this out as not an issue.

**Comment by fegg** [comment]
Hello, I use css-loader 0.23.1, Also encountered the same problem, @blainekasten you use css-loader version? to resolve this question?
