### ISSUE TITLE
Can't build LESS/CSS. Getting ReferenceError: window is not defined

### ISSUE THREAD

**Issue by fruser** [webpack/extract-text-webpack-plugin#124]
Hi,

I'm trying to build one of the `vendor` css files using `webpack` and `ExtractTextPlugin` but the build fails with the `RefferenceError: window is not defined`.

My **webpack.config.js** part of the LESS configuration is below:
```
{
        test: /\.less$/,
        loader: ExtractTextPlugin.extract(
          'style-loader',
          'css-loader!' +
          'autoprefixer-loader!' +
          'less-loader'
        )
}
```

I'm _requiring_ my `styles.js` file, which requires `vendor.less` file (which requires CSS file from `bower` directory):

**styles.js**:
`require('../../../less/vendor.less');`

**vendor.less**
`@import (css) "~vendor-ui-bootstrap/dist/css/arena.css";`

Below I included the error message (almost forgot to include that I use Windows/Node5):
https://gist.github.com/fruser/fa1a30ed01f8bdba7223

And if I don't use the plugin everything compiles no problem.

Am I missing something in my `webpack.config.js` file?

Thank you!

**Comment by fruser** [comment]
I was able to resolve this. The problem was with the the `webpack.config.js` file where I had 'jquery' reference in alias section:

**webpack.config.js**:
```
new webpack.ProvidePlugin({
    '_': 'underscore',
    $: 'jquery',
    jQuery: 'jquery',
    'window.jQuery': 'jquery'
}),
...
alias: {
  //'jquery': 'jquery/jquery', - no need to have as I'm using the plugin
  'jquery-bbq': 'jquery-bbq/jquery.ba-bbq',
  'jquery.cookie': 'jquery.cookie/jquery.cookie',
  'jquery.chosen': 'chosen/chosen.jquery.min',
  'jquery.colorpicker': 'jQuery-ColorPicker/colorpicker',
  'jquery.fileupload': 'blueimp-file-upload/js/jquery.fileupload',
  'jquery.scrollTo': 'jquery.scrollto/jquery.scrollTo',
  'jquery.tagsinput': 'jquery-tags-input/src/jquery.tagsinput',
  'jquery.tablednd': 'TableDnD/js/jquery.tablednd',
  'jquery.ui': 'jquery-ui/jquery-ui',
  'jquery.ui.widget': 'blueimp-file-upload/js/vendor/jquery.ui.widget',
  'jquery.validate': 'jquery-validation/dist/jquery.validate',
  'json2': 'JSON-js/json2'
},
```

Once I deleted the reference the build process succeeded.

**Comment by cchamberlain** [comment]
@fruser - Thanks this fixed same frustrating issue for me.

**Comment by mgol** [comment]
@fruser you found a workaround but that won't help everyone. I need to use aliases and I have the same problem. I think the issue should be reopened.

**Comment by eminoda** [comment]
ERROR in ./src/css/user.css
Module build failed: ReferenceError: window is not defined

My webpack config：
`let webpack = require('webpack');
let ExtractTextPlugin = require('extract-text-webpack-plugin');

var path = require('path');
module.exports = {
  entry: {
    'app': './src/app.js'
  },
  output: {
    path: path.join(__dirname, "/public/javascripts"),
    filename: 'app.bundle.js'
  },
  module: {
    loaders: [{
      test: /\.js$/,
      // excluding node_modules here because otherwise all external libraries will also go through Babel, slowing down compilation.
      exclude: /node_modules/,
      loader: 'babel-loader'
    }, {
      test: /\.css$/,
      // loader: ["style-loader", "css-loader"]
      use: ExtractTextPlugin.extract(["style-loader", "css-loader"])
    }, {
      test: /\.scss$/,
      // loader: ["style-loader", "css-loader", "sass-loader"]
      use: ExtractTextPlugin.extract(["style-loader", "css-loader", "sass-loader"])
    }]
  },
  plugins: [
    // new webpack.optimize.UglifyJsPlugin({
    //   compress: {
    //     warnings: false,
    //   },
    //   output: {
    //     comments: false,
    //   },
    // }),
    new ExtractTextPlugin("../public/stylesheets/[name].css")
  ]
};
`
How can  i fix？

**Comment by eminoda** [comment]
const ExtractTextPlugin = require('extract-text-webpack-plugin');
 
// Create multiple instances 
const extractCSS = new ExtractTextPlugin('stylesheets/[name]-one.css');
const extractLESS = new ExtractTextPlugin('stylesheets/[name]-two.css');
 
module.exports = {
  module: {
    rules: [
      {
        test: /\.css$/,
        use: extractCSS.extract([ 'css-loader', 'postcss-loader' ])
      },
      {
        test: /\.less$/i,
        use: extractLESS.extract([ 'css-loader', 'less-loader' ])
      },
    ]
  },
  plugins: [
    extractCSS,
    extractLESS
  ]
};
