### ISSUE TITLE
Issue with stylus modules

### ISSUE THREAD

**Issue by geowarin** [webpack/extract-text-webpack-plugin#126]
Hello!

Today, I ran into a strange bug with stylus, including a simple module:

```
ERROR in ./~/css-loader!./main.styl
Module not found: Error: Cannot resolve 'file' or 'directory' ./nib in /Users/geowarin/dev/react/extract-bug
 @ ./~/css-loader!./main.styl 3:10-63

ERROR in ./main.styl
Module build failed: ModuleNotFoundError: Module not found: Error: Cannot resolve 'file' or 'directory' ./nib in /Users/geowarin/dev/react/extract-bug
```

The minimal setup to reproduce the issue is available here:
https://github.com/geowarin/extract-bug

I believe this is a very classical example of stylus + extract plugin working together.
The strangest part is that it was working perfectly **yesterday**. Then I npm installed again and everything broke (using npm 3.3.12).

I think it's related to the extract plugin since the stylus part is working otherwise.

Tell me if there is anything more I can do to help.

**Comment by geowarin** [comment]
It also breaks with npm 2. See the 4.0 build on travis:
https://travis-ci.org/geowarin/extract-bug/builds/92691285

**Comment by albizures** [comment]
try `loader: ExtractTextPlugin.extract('style-loader', 'css-loader!stylus-loader')`

**Comment by geowarin** [comment]
I managed to get it working with the following configuration.

webpack.dev.js:

```js
var webpack = require('webpack');
var jeet = require('jeet');
var nib = require('nib');

module.exports = {
  module: {
    loaders: [{
      test: /\.styl$/,
      loaders: ['style-loader', 'css-loader', 'stylus-loader']
    }]
  },
  stylus: {
    use: [jeet(), nib()]
  }
};
```

webpack.prod.js:
```js
var webpack = require('webpack');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var jeet = require('jeet');
var nib = require('nib');

module.exports = {
  plugins: [
    new ExtractTextPlugin('styles.css')
  ]
  module: {
    loaders: [{
      test: /\.styl$/,
      loader: ExtractTextPlugin.extract('css-loader!stylus-loader')
    }]
  },
  stylus: {
    use: [jeet(), nib()]
  }
};
```

I don't really know why there are differences in the loaders but I'm closing this.
Thanks for your input @albizures

**Comment by crapthings** [comment]
i can't get it work, here is my config.

	var ExtractTextPlugin = require("extract-text-webpack-plugin")

	var poststylus = require('poststylus')

	module.exports = {
		cache: true,
		context: __dirname + '/app',
		entry: './index.js',
		output: {
			path: __dirname + '/app',
			filename: 'bundle.js'
		},
		module: {
			loaders: [
				{ test: /\.js$/, loader: 'babel', exculde: /node_modules/, query: { presets: ['es2015'], plugins: ['add-module-exports'] } },
				{ test: /\.html$/, loader: 'html', exculde: /node_modules/ },
				{ test: /\.css$/, loader: 'style!css!postcss', exculde: /node_modules/ },
				// { test: /\.styl$/, loader: 'style!css!stylus', exculde: /node_modules/ }
				{ test: /\.styl$/, loader: ExtractTextPlugin.extract('css-loader!stylus-loader'), exculde: /node_modules/ }
				// { test: /\.styl$/, loader: ExtractTextPlugin.extract('stylus', 'css-loader!stylus-loader'), exculde: /node_modules/ }
			]
		},
		plugins: [
	        new ExtractTextPlugin('bundle.css')
	    ],
		stylus: {
			use: [poststylus(['autoprefixer', 'postcss-short', 'postcss-sorting', 'postcss-cssnext', 'rucksack-css'])]
		}
	}

**Comment by Mannaio** [comment]
@crapthings i have the same config in the webpack.config.dev.js and i can not generate my style.css, have you found a solution?

**Comment by crapthings** [comment]
@Mannaio yes this work for me

https://github.com/crapthings/webpack-choo-undefined/blob/master/webpack.config.dev.js
