### ISSUE TITLE
Module build failed: TypeError: text.forEach is not a function

### ISSUE THREAD

**Issue by Oleksandr-Silin** [webpack/extract-text-webpack-plugin#131]
I have webpack config
```javascript
    module: {
        loaders: [
            ...
            {
                test: /\.css$/,
                loader: ExtractTextPlugin.extract("style-loader", "css-loader")
            },
            ...
        ]
    },
    plugins: [
        ...
        new ExtractTextPlugin("[name].css", {
            disable: false,
            allChunks: true
        })
    ]
```
and app.js file:
```javascript
var React = require('react');
require('../css/colors.css');
require('../css/main.css');
require('../css/tags.css');
Router.run(function (Handler, state) {
    React.render(<Handler/>, document.getElementById('my-app'));
});
```
with such configuration i receive error for each css file in console output:
*Module build failed: TypeError: text.forEach is not a function
    at Object.<anonymous> (/home/src/app/node_modules/extract-text-webpack-plugin/loader.js:100:11)
    at Compiler.<anonymous> (/home/src/app/node_modules/webpack/lib/Compiler.js:214:10)
    at /home/src/app/node_modules/webpack/lib/Compiler.js:403:12....*

If I remove configuration, styles are inlined into head of html file.
```javascript
{
 disable: false,
 allChunks: true
}
```

How should i update or fix it?

**Comment by sheerun** [comment]
I have the same issue

**Comment by em-yuanbo** [comment]
i get the same error, and i found out that the text was not array or string but an object like ` { root: 'styles__root___2bUDW' }`.

and i just change this line https://github.com/webpack/extract-text-webpack-plugin/blob/master/loader.js#L98  from `if(typeof text === "string"){` to  `if(typeof text === "string" || !Array.isArray(text)){`  and the error gone.

but i don't know whether it is correct or not.

**Comment by GreenGremlin** [comment]
Adding css-loader to the ignore option fixed this, for me.

``` JavaScript
    new SplitByPathPlugin(
      [{ name: 'vendor', path: __dirname + '/node_modules' }],
      { ignore: [__dirname + '/node_modules/css-loader'] }
    ),
```

**Comment by Oleksandr-Silin** [comment]
@GreenGremlin Thank you! It helped me.

**Comment by nadavsinai** [comment]
thanks @GreenGremlin !

**Comment by sloot14** [comment]
Thank you! @GreenGremlin

**Comment by jknight12882** [comment]
I am getting this issue and am not using the `SplitByPathPlugin`. This is with `Webpack@3.x.x`

**Comment by sresant** [comment]
I am in the same boat as @jknight12882. Seems to be under watch mode specifically. I added some logging to see what the text object is and it is a function.
