### ISSUE TITLE
Error: Cannot find module 'webpack-sources' on v1.0.0

### ISSUE THREAD

**Issue by jonathanong** [webpack/extract-text-webpack-plugin#143]
thank god for greenkeeper for letting me know :)

pretty sure you're missing a `npm i --save webpack-sources`

**Comment by fortruce** [comment]
I made a PR to fix this issue: #142.

**Comment by GuilhermeMedeiros** [comment]
:+1:

**Comment by TrejGun** [comment]
:+1:

**Comment by adanperez** [comment]
:+1:

**Comment by cesarandreu** [comment]
:+1:

**Comment by JMingZI** [comment]
+1

**Comment by alexbet** [comment]
+1

**Comment by afc163** [comment]
+1

**Comment by oliverbenns** [comment]
+1

**Comment by gajus** [comment]
@sokra You have bumped the last version. Can you patch it? Add the missing dependency.

**Comment by samarpanda** [comment]
I bumped with the same issue. Was struggling for a project setup today. Please release this patch asap. Thanks!

**Comment by samarpanda** [comment]
Anyways, i have installed `webpack-sources` explicitly for now i.e `npm install --save-dev webpack-sources`. So, its working. Just wanted to give a heads up.

**Comment by contra** [comment]
Seriously, how is this still not fixed?

**Comment by avindra** [comment]
Sokra probably hasn't seen it yet, I imagine the person behind Webpack is
quite busy these days.

Thanks for your work and one of the most significant contributions to
JavaScript in recent memory.

**Comment by bebraw** [comment]
The PR fixing this was merged (https://github.com/webpack/extract-text-webpack-plugin/pull/142). Fingers crossed he can publish a new version containing it soon. :smile:

**Comment by sokra** [comment]
Published...

**Comment by kiki-le-singe** [comment]
@sokra thanks for your time

**Comment by Evllis** [comment]
+1
