### ISSUE TITLE
No CSS files generated from plugin by using css-loader and sass-loader

### ISSUE THREAD

**Issue by cwallervand** [webpack/extract-text-webpack-plugin#155]
Hi.

I am trying to generate one main css file for my application based on my sass files by using the ExtractTextPlugin. I have looked at many examples and googled for hours, and I cant seem to find other people with the same issue, which is that no css file is generated.  I must be missing some small but important detail. Any help is greatly apprectiated. Here is my webpack config (in its entirety):

```
var webpack = require('webpack');
var ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {
    entry: {
      config: './app/config/config.js',
      betaling: './app/index.jsx',
    },
    output: {
      path: __dirname + '/wwwroot',
      filename: './dist/[name].bundle.js'
    },
    externals: {
      "config": "config",
    },
    debug: true,
    devtool: 'cheap-module-eval-source-map',
    module: {
      preLoaders: [
        {
          test: /\.jsx?$/,
          loader: "eslint-loader",
          exclude: /node_modules/
        }
      ],
      loaders: [
        {
          test: /\.jsx?$/,
          exclude: /(node_modules)/,
          loader: 'babel-loader',
          query: {
            presets: ['es2015', 'react']
          }
        },
        {
          test: /\.yml$/,
          loader: "json!yaml"
        },
        {
          test: /\.scss$/,
          exclude: /(node_modules)/,
          // loader: "style!css!sass",
          loader: ExtractTextPlugin.extract('css!sass'),
        }
      ]
    },
    plugins: [
      new webpack.DefinePlugin({
        'process.env.ENVIRONMENT': '"'+process.env.NODE_ENV+'"'
      }),
      new ExtractTextPlugin('style.css', {
        allowChunks: true
      })
    ],
    resolve: {
        extensions: ['', '.js', '.jsx', '.scss']
    }
};

```

Filestructure:
```
...
app/
|    +--sass/
     |    +-- main.scss
     |    +-- *.scss
wwwroot/
webpack.config.debug.js
...
```

I also include the main.scss file in my root React container (dont know if I need this or not regarding the extract-plugin.)
```
import React from 'react';
import './sass/main.scss';

class App extends React.Component {
  render() {
    return (
      <div>
        {this.props.children}
      </div>
    );
  }
}

App.propTypes = {
  children: React.PropTypes.element.isRequired,
};

export default App;
```

PS. I know that it is not necessary to create css files in debug. I intend to do this for production, but i just want it to work first :P

**Comment by cwallervand** [comment]
In all my wisdom I did not realize that the dev-server did not write files to disk. The setup is working when I do not run the dev-server

**Comment by phun-ky** [comment]
@cwallervand glad that was fixed, but why can't the dev server write file to disk? 

I am trying to write a styleguide with `node-kss`, and you want to write a styleguide when developing, not when you are in production, isn't that limitation counter-productive?

I am trying to use this plugin to extract and create the css files when using the dev server, so that the styleguide can be updated accordingly

**Comment by cwallervand** [comment]
Not sure I understand your question @phun-ky. I think that the webpack-dev server serves the assets from memory, and not from disk. 

As to how we are using the plugin, here is the relevant parts from our production webpack configuration (where we use the extract-text plugin):

```js
const ExtractTextPlugin = require('extract-text-webpack-plugin');
...
const config = {
  module: {
    loaders: [
      {
        test: /\.scss$/,
        loader: ExtractTextPlugin.extract('style', `css!postcss!sass?sourceMap&includePaths[]=${bourbonPath}&includePaths[]=${neatPath}`, {
          publicPath: '',
        }),
      },
    ],
  },
  postcss: [
    autoprefixer(),
  ],
  plugins: [
    new ExtractTextPlugin('[name].bundle.[chunkhash].css'),
  ],
};
```

In development we do not use the extract-textx plugin, instead we inline the styling. Here is a snippt of the relevant parts from our development config for webpack:

```js
const config = {
  module: {
    loaders: [
      {
        test: /\.scss$/,
        loader: `style!css!postcss!sass?sourceMap&includePaths[]=${bourbonPath}&includePaths[]=${neatPath}`,
      },
    ],
  },
  postcss: [
    autoprefixer(),
  ],
};
```

In our application container (AppContainer, we use React) we import our main Sass file:
```js
import './styles/main.scss';
```

`main.scss` references other scss files. These can be from the local project or from an imported npm package  (we use our own styleguide written with kss ;) ) 


Hope this was of help to you.

**Comment by phun-ky** [comment]
The problem with this approach, is that when you are trying to view the
generated styleguide, the styles you have created is not used by the KSS
template. The only way to do that is to include a css file, but the
given approach is that the produced and required css file is not
available until you do a production build, making the development of a
styleguide a bit tiresome 

Den 2016-06-20 14:31, skrev Christian Wallervand:

> Not sure I understand your question @phun-ky [1]. I think that the webpack-dev server serves the assets from memory, and not from disk. 
> 
> As to how we are using the plugin, here is the relevant parts from our production webpack configuration (where we use the extract-text plugin):
> 
> const ExtractTextPlugin = require('extract-text-webpack-plugin');
> ...
> const config = {
> module: {
> loaders: [
> {
> test: /\.scss$/,
> loader: ExtractTextPlugin.extract('style', `css!postcss!sass?sourceMap&includePaths[]=${bourbonPath}&includePaths[]=${neatPath}`, {
> publicPath: '',
> }),
> },
> ],
> },
> postcss: [
> autoprefixer(),
> ],
> plugins: [
> new ExtractTextPlugin('[name].bundle.[chunkhash].css'),
> ],
> };
> 
> In development we do not use the extract-textx plugin, instead we inline the styling. Here is a snippt of the relevant parts from our development config for webpack:
> 
> const config = {
> module: {
> loaders: [
> {
> test: /\.scss$/,
> loader: `style!css!postcss!sass?sourceMap&includePaths[]=${bourbonPath}&includePaths[]=${neatPath}`,
> },
> ],
> },
> postcss: [
> autoprefixer(),
> ],
> };
> 
> In our application container (AppContainer, we use React) we import our main Sass file:
> 
> import './styles/main.scss';
> 
> main.scss references other scss files. These can be from the local project or from an imported npm package (we use our own styleguide written with kss ;) ) 
> 
> Hope this was of help to you. 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].
 

Links:
------
[1] https://github.com/phun-ky
[2]
https://github.com/webpack/extract-text-webpack-plugin/issues/155#issuecomment-227128863
[3]
https://github.com/notifications/unsubscribe/ABonbfeEMLI1GnIIqXxLwjUhUk3_Kacpks5qNogTgaJpZM4HgZ2-

**Comment by gbhipolitoglyph** [comment]
thank you cwallervand, because of all the answers I've googled, nobody, not one, told me that you have to import './sass/main.scss';
that very simple piece of code. Not one, noone
