### ISSUE TITLE
Only the last SCSS chunk gets written to output CSS

### ISSUE THREAD

**Issue by davidfateh** [webpack/extract-text-webpack-plugin#156]
I appears that when I run this plugin with multiple SCSS files only the last file to be read by extract-text is output into my CSS file. The log looks like: 
```
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 15.9 kB [rendered]
        [0] ./~/css-loader?modules!./~/sass-loader!./src/components/myComponent/myComponent.scss 14.4 kB {0} [built]
        [1] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]

Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 1.82 kB [rendered]
        [0] ./~/css-loader?modules!./~/sass-loader!./test/styling.scss 311 bytes {0} [built]
        [1] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
```

Only `styling.scss` will get output to the static CSS file while `myComponent.scss` does not.

My loaders are set up as such:
```
module: {
   loaders: [{
     test: /\.css$|\.scss$/,
            loader: extractSass.extract('style', 'css?modules!sass'),
   }],
plugins: [
   new ExtractTextPlugin('app.css'),
]
}
```
Is it possible that each iteration of a chunk overwrites the existing styles that will go into the CSS file?

**Comment by silvenon** [comment]
@davidfateh Have you tried passing `{ allChunks: true }` as an option?

**Comment by davidfateh** [comment]
@silvenon Yes, but that didn't seem to work. I haven't looked at this problem in a while so I'm going to close it for now. I'll reopen if I run into it in the future... ended up taking a different route.

**Comment by silvenon** [comment]
@davidfateh are you using webpack v2? Something similar happened to me, downgrading to v1 worked.

**Comment by davidfateh** [comment]
@silvenon No, I'm using 1.12.4. Like I said I kind of walked away from this for now. I'm planning on coming back to it though so if it happens again I'll dive a little deeper and try to give more info on the problem if it happens again.
