### ISSUE TITLE
XHTML 

### ISSUE THREAD

**Issue by Krisa** [webpack/extract-text-webpack-plugin#160]
ExtractTextPlugin adds following tag automatically to my index.html: `<link href="styles.css" rel="stylesheet">`. Would it be possible to close the link tag like following: `<link href="styles.css" rel="stylesheet" />` ? Or as a workaround, to not add a tag at all (I can add that manually too in my template index) ?

**Comment by koenpunt** [comment]
The `<link ..>` is added by https://github.com/ampedandwired/html-webpack-plugin 
I've opened a PR over there to add a `xhtml` option

**Comment by Krisa** [comment]
Amazing! Thank you! (closing this issue as we have the PR there)
