### ISSUE TITLE
Update peerDependencies for webpack2

### ISSUE THREAD

**Issue by ju1ius** [webpack/extract-text-webpack-plugin#168]
Hi,
although the plugin works quite well with webpack2.1.0-beta4, it specifies a peerDependency to webpack 1, causing CI build to fail:
```
npm ERR! peerinvalid Peer extract-text-webpack-plugin@1.0.1 wants webpack@^1.9.11
```

**Comment by timbru31** [comment]
Running into the same issue, the ExtractTextPlugin works fine though.

**Comment by amio** [comment]
There is a PR #157 already, But seems nobody merge it.

**Comment by amio** [comment]
Acturally #147 may solve this too.

**Comment by Kovensky** [comment]
This also complicates use with npm 2 -- installing extract-text-webpack-plugin will "update" `webpack@^2.1.0-beta ` into one that matches the peerDependency.

**Comment by developer94404** [comment]
just a note:

using npm 4.x on my system:

1. on my system, installing using node v4.x fails, and gives:
npm WARN peerDependencies The peer dependency webpack@^1.9.11 included from extract-text-webpack-plugin will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! code EPEERINVALID


2. and then using node v7.x is successful, but gives:
+-- extract-text-webpack-plugin@1.0.1 
`-- UNMET PEER DEPENDENCY webpack@2.2.0
