### ISSUE TITLE
Cannot resolve module [object Object]

### ISSUE THREAD

**Issue by raphaklaus** [webpack/extract-text-webpack-plugin#215]
Hi there! I'm trying to execute a webpack with extract-text, but I'm getting "Cannot resolve module '[object Object]'".

Here is a fragment.
```
    loaders: [{
      test: /\.css$/,
      loader: ExtractTextPlugin.extract({
        notExtractLoader: "style-loader",
        loader: "css-loader"
      })
    }]
```

Version of this plugin: 1.0.1
Node: 6.2.0. Tested in 4.4.0. And the same.

**Comment by raphaklaus** [comment]
Well, for some reason version 1.0.1 doesn't works with webpack 1.x
I've upgraded to extract-text-webpack-plugin@v2.0.0-beta.2 and webpack@v2.1.0-beta.19 and worked perfectly.

**Comment by Eschon** [comment]
Hi I'm having the same issue. I also use version 1.0.1 and my node version is 6.2.2.
Using v2.0.0-beta.2 or v2.0.0-beta.3 won't work for me because of #214 

Here's the loader config for the plugin:
```
{
  test: /\.css$/,
  loader: ExtractTextPlugin.extract({
    fallbackLoader: 'style-loader',
    loader: 'css-loader!postcss-loader'
  })
}
```

Please let me know if I can supply any additional information for resolving this issue.

**Comment by Eschon** [comment]
I managed to fix it by changing my loader config to
```
{
  test: /\.css$/,
  loader: ExtractTextPlugin.extract('style', 'css-loader!postcss-loader')
}
```

Still I think there is an issue that should be resolved, because my initial config was pretty similar to what you have in the README.md

**Comment by Kovensky** [comment]
You have to upgrade both `extract-text-webpack-plugin` to `^v2.0.0-beta.3` and `webpack` to `^v2.1.0-beta.19` to fix #214.

**Comment by Eschon** [comment]
@Kovensky I know that #214 would have been fixed if I switched to the newest webpack beta but I don't like using beta versions of packages in production if I can avoid it.

And `ExtractTextPlugin.extract('style', 'css-loader!postcss-loader')` works without problems in `extract-text-webpack-plugin@1.0.1`

**Comment by narek11** [comment]
@Kovensky doesn't `ExtractTextPlugin.extract` accepts only a single config argument ?

**Comment by Kovensky** [comment]
@narek11 yes, as of the version 2 beta, and it complains at you if you do give more than one argument. Previous versions accept (up to) 3 arguments.

**Comment by arahansen** [comment]
I'm having this issue as well on webpack@1.13.1 and extract-text-webpack-plugin@1.0.1

I would rather not upgrade to either beta right now (upgrading webpack broke my build). Is there a workaround for this issue? Should I revert the plugin to an earlier version? @Eschon 's proposed fix didn't seem to do it for me.

**Comment by Kovensky** [comment]
Use the documentation from the `webpack-1` branch when using the 1.x version: https://github.com/webpack/extract-text-webpack-plugin/blob/webpack-1/README.md

**Comment by Prairie-Falcon** [comment]
I'm in exactly the same position as raphaklaus was Jul 17: Node 6.2.0, extract-text-webpack-plugin@1.0.1, using the same fragment he used, and getting the same error message. I'm also in the same position as arahansen on Jul 27: I need to use a stable release in production. Is there a workaround?

**Comment by Prairie-Falcon** [comment]
New report. I got a workaround to work. See [my documentation here](https://github.com/webpack/extract-text-webpack-plugin/issues/173).

**Comment by RyanCCollins** [comment]
I got into this same bind, wasn't able to update to the latest v of webpack and @Prairie-Falcon's guide saved me.  Kudos!!

**Comment by bilgorajskim** [comment]
Not sure if this will help, but in my case this was caused by having these lines in webpack config:
```
module.exports = {
  resolve: { fallback: path.join(__dirname, "node_modules") },
  resolveLoader: { fallback: path.join(__dirname, "node_modules") }}
...
```
Removing them fixed the problem.

**Comment by TNT-Likely** [comment]
@raphaklaus not work when i update extract-text-webpack-plugin to 2.0.0-beta.2,show errors
![qq20161228-1](https://cloud.githubusercontent.com/assets/9278923/21518047/9eb8eef4-cd1e-11e6-8c39-6a0b1e4aaa41.png)
<img width="557" alt="0702035e-62c4-417c-803d-b12a71b190e1" src="https://cloud.githubusercontent.com/assets/9278923/21518055/a8da4e96-cd1e-11e6-8795-03314792f064.png">

**Comment by aronlmin** [comment]
having issue with webpack v1.14.0 & extract-text-webpack-plugin v1.0.1 on windows when running `webpack --watch` within my react application .jsx file





```javascript
// webpack.config.json
{
  // . . .
  module: {
     loaders: [
      {
        test: /\.jsx?$/,
        loader: 'babel-loader'
      },
      {
        test: /\.scss$/,
        loader: ExtractTextPlugin.extract({
          fallbackLoader: 'style-loader',
          loader: 'css-loader!sass-loader'
        })
      }
    ]
  },
  plugins: [
    new ExtractTextPlugin('./public/style.css')
  ]
}
```
Error output in terminal:
```
ERROR in ./src/Index.jsx
Module not found: Error: Cannot resolve module '[object Object]' in C:\Users\ALilland\Documents\application\src
 @ ./src/Index.jsx 15:0-26

**Comment by wheelerlaw** [comment]
@TNT-Likely Did you add the `ExtractTextPlugin` plugin to the list of plugins? Do something like this in your webpack.config.js:
```
config.plugins = [
    new ExtractTestPlugin('css/[name].[hash].css'),
    <other plugins>
]
```
@aronlmin You are using the wrong syntax for the `extract` method call. The syntax you are using is for the latest version of the `extract-text-webpack-plugin`. For version 1, change it to look like this:
```
loader: ExtractTextPlugin.extract('style-loader', 'css-loader!sass-loader')
```
