### ISSUE TITLE
[2.0 beta] Errors thrown from loader-runner not caught/handled

### ISSUE THREAD

**Issue by oh-ren** [webpack/extract-text-webpack-plugin#218]
**Bug report**
2.0.0-beta.3 w/ wp 2.1.0-beta.20

Issue arised after upgrading to `wp` > `2.1.0-beta.15` & `extract-text-webpack-plugin@beta`.

**Current behavior:**
Errors thrown from `loader-runner` do need seem to be caught, which causes `webpack -w` to exit. They do (still) get caught when **not** using the plugin. Example:
> [...]\node_modules\loader-runner\lib\LoaderRunner.js:90
>                        throw e;
>                        ^
>
> TypeError: Cannot read property '[...]\node_modules\extract-text-webpack-plugin' of null 
> [...]

**Expected/desired behavior:**
Error message (`"Can't resolve..."`) in red, without exiting the watch process (like before).

**Reproduce**
Point to an invalid path in an `url(...)` rule.

**Comment by valery-vitko** [comment]
Not quite sure if this could help. Stumbled upon this exact issue and had knocked off a bit smelly [workaround](https://github.com/Steinpilz/extract-text-webpack-plugin/commit/2753e84b2f570b782fb4d31ec9830afeba6a61b9) (`npm i -D git+ssh://git@github.com/Steinpilz/extract-text-webpack-plugin.git#type-error-investigations`).

**Comment by oh-ren** [comment]
Cool, will check it out, thanks! (Though I expect will be (properly) fixed in codebase soon anyways.. :))

**Comment by derpoho** [comment]
+ 1 here with beta.3...

Is there any implemented workaround yet?

**Comment by oh-ren** [comment]
@valery-vitko's workaround seems to work for me.

**Comment by kesne** [comment]
This seems related to #211.

**Comment by Zyphrax** [comment]
@valery-vitko thank you for the workaround! It was driving me crazy that the dev-server would stop running because of my typos.

The npm command you supplied didn't work for me, this did (in case anyone else runs into that):
`npm i -D github:Steinpilz/extract-text-webpack-plugin.git#type-error-investigations`

**Comment by Zyphrax** [comment]
Could you please send this in as a pull request?
That would be great!

**Comment by valery-vitko** [comment]
@Zyphrax, yes, no problem - #242

**Comment by Zyphrax** [comment]
Great, thank you!

**Comment by oh-ren** [comment]
Closing. This seems to be no issue anymore in latest beta.
