### ISSUE TITLE
Merge output from various instances

### ISSUE THREAD

**Issue by mgol** [webpack/extract-text-webpack-plugin#227]
In various files I import SCSS or CSS files; there is a different loader config for each of them in the Webpack config: for CSS I use `loaders: ['style', 'css?sourceMap']` and for SCSS: `loaders: ['style', 'css?sourceMap', 'postcss', 'sass?sourceMap']`. I want to use `extract-text-webpack-plugin` for each of them but have the result concatenated into one file.

This doesn't seem to be possible: If I wrap the loaders with `ExtractTextPlugin.extract`, I'm only left with a file generated from CSS (it seems the SCSS one gets overwritten). If I create separate instances for CSS & SCSS files and use `extract` on them, I have to provide separate paths for them or the second one will overwrite the first one.

There should be a way to append to the file generated by previous plugin instances.

**Comment by mgol** [comment]
Hmm, this may be a dupe of #179.

**Comment by bebraw** [comment]
Yeah, let's close as a duplicate.
