### ISSUE TITLE
WebPack with Angular 2: Loading CSS causes error, 'Expected 'styles' to be an array of strings.'

### ISSUE THREAD

**Issue by aconfee** [webpack/extract-text-webpack-plugin#234]
Environment:
Angular 2
WebPack
https://github.com/aconfee/MEANTemplateV3

Problem:
(See images provided) I cannot load my SCSS when using ExtractTextPlugin together with css-to-string-loader. This error is originally caused by the css and style-loaders not returning strings, which Angular 2 expects. css-to-string-loader is used to convert the output of the loader to a string.

ExtractTextPlugin then converts the final output to something other than a string, causing this error again. 

Road So Far:
Look at the attached images
![screen shot 2016-08-19 at 2 18 58 pm](https://cloud.githubusercontent.com/assets/3591960/17821838/5523e62a-6619-11e6-9e4c-434ffc9cafb1.png)
![screen shot 2016-08-19 at 2 22 18 pm](https://cloud.githubusercontent.com/assets/3591960/17821839/55267304-6619-11e6-9088-f8cead731138.png)

. The currently uncommented lines 35 and 40 of webpack.common.js WORK. As soon as I swap them with their commented counterparts, the error is caused. I'm still completely new to Webpack and trying to understand what is happening here, and what the best practice around this is. Why does Angular 2 need text? How can I resolve this issue using your tool? And I understand that your tool pulls the styles out of the compiled JS, but why were the styles compiled into JS to begin with? (Sorry, I'm really new and any insight here is appreciated).

**Comment by aconfee** [comment]
Here's the full config being used: https://github.com/aconfee/MEANTemplateV3/blob/master/config/webpack.common.js. 

The finishing touches and output are included in: https://github.com/aconfee/MEANTemplateV3/tree/master/config

**Comment by aconfee** [comment]
Also, as a general question, why is the style-loader normally used with the css-loader? Is it faster to inject styles directly into the html? At what point does that become slower? What are best practices around this? (Any advice at all about best practices for scss/css and typescript/js would be much appreciated! Also, any details on what's happening under the hood.)

**Comment by Kovensky** [comment]
You are giving wrong parameters to `.extract`. The first argument is a "fallback loader" used when the css is not extracted (for example, if you give the disable option to the plugin). The second is the sequence of loaders that generates the result css.

However, it seems to me the css-to-string-loader is not compatible with extracting. The point of extracting is to remove the css text from the bundle, but in this case you actually need the text. You also don't want to pass it through style-loader since you want the css itself. I assume angular will do for you what style-loader would have done.

**Comment by TameshwarNirmalkar** [comment]
HI @aconfee,
To answer your question why style-loader uses css-loader,
style-loader is to inject the <style></style> and <link href="xyz.css"> in html page.

css-loader is uses for extract css file which is being used in another file, for example.
abc.css has imported another css file inside it like.
@import 'xyz.css';

**Comment by josueadelima** [comment]
@aconfee don't use the documentation configuration, with that configuration if you have file-loader using hash, then url's inside css will not have the hash and you will end with broken background-images, leave my config here:

```
{
        test: /\.(png|jpe?g|gif|svg|woff|woff2|ttf|eot|ico)$/,
        loader: 'file-loader?name=assets/[name]-[hash].[ext]'
      },
      {
        test: /\.css$/,
        exclude: helpers.root('src', 'app'),
        loader: ExtractTextPlugin.extract({ fallbackLoader: 'style-loader', loader: 'css-loader?sourceMap' })
      },
      {
        test: /\.sass$/,
        include: helpers.root('src', 'app'),
        loader: ['css-to-string-loader','css-loader','sass-loader'] 
      },
      {
        test: /\.css$/,
        include: helpers.root('src', 'app'),
        loader: ['css-to-string-loader','css-loader']
      }
```
Hope works for others

**Comment by smasala** [comment]
For SASS this worked for me:

```
        {
          test: /\.sass$/,
          include: helpers.root("node_modules"),
          loader: ['css-to-string-loader','css-loader','sass-loader']
        },
```

**Comment by josueadelima** [comment]
@smasala please change loader: (singular) to loaders: (plural) missed that!

**Comment by smasala** [comment]
@josueadelima :+1:  Didn't see that in my webpack config either. It seems to work with both though :)

**Comment by k3lh4m** [comment]
For anyone that still has this problem, check this out 

Hope it helps other people, like it did do for me 

https://stackoverflow.com/questions/41516346/error-expected-styles-to-be-an-array-of-strings/#43867625
