### ISSUE TITLE
Support default exports

### ISSUE THREAD

**Issue by AlexanderMattoni** [webpack/extract-text-webpack-plugin#244]
Im attempting to use the plugin in conjunction with the Typed CSS Module plugin (https://github.com/Quramy/typed-css-modules).

The typed-css-modules plugin creates Typescript definitions for a default export, which is the same way that the styles loader does it. Using this plugin breaks support.

I was able to get it working by changing this line: 

```
resultSource += "\nmodule.exports = " + JSON.stringify(text.locals) + ";";
```

to 

```
resultSource += "\nmodule.exports.default = " + JSON.stringify(text.locals) + ";";
```

but I'd rather there be an option to do this. Any plans to support this?

Thanks!

**Comment by Kovensky** [comment]
If you are using `import` syntax, you should be doing namespace imports for CSS modules.

`import * as styles from './styles.css'`
