### ISSUE TITLE
why there is a plugin and a loader?

### ISSUE THREAD

**Issue by zzzgit** [webpack/extract-text-webpack-plugin#256]
in the configuration file,there will be a loader and a plugin
what is the purpose of the loader and the plugin
what is the difference between them?

**Comment by MoOx** [comment]
You must use both. Both are useful at different moment of webpack runtime. No plugin, no extraction.

**Comment by nblackburn** [comment]
I think the point @zzzgit is raising is that it's pretty horrible to work with when put next to any other webpack plugin (two configurations, initialized outside of the config and then needs placing in two places just for it to work all whilst feeling as though i am fighting with it).
