### ISSUE TITLE
chunk.isInitial is not a function

### ISSUE THREAD

**Issue by Awk34** [webpack/extract-text-webpack-plugin#261]
I'm getting this error when trying to build my app:

```
var shouldExtract = !!(options.allChunks || chunk.isInitial());
                                                  ^

TypeError: chunk.isInitial is not a function
    at <myApp>\node_modules\extract-text-webpack-plugin\index.js:246:55
    ...
```

I'm using `webpack`@`2.1.0-beta.25` & `extract-text-webpack-plugin`@`2.0.0-beta.4`

I can provide more details if they're needed

**Comment by Awk34** [comment]
My fault. I was using `webpack-stream`, which I wasn't aware includes it's own dependency on Webpack@1. Running Webpack from the Node interface fixed this issue.

**Comment by allahbaksh** [comment]
What do you mean running "webpack from node interface". I am having similar problem

**Comment by Roy9102** [comment]
@allahbaksh It means your global webpack (terminal cli) is the webpack@1.xxx, you need to upgrade your webpack,  you can check out your webpack version by 'webpack -v'

**Comment by Awk34** [comment]
@allahbaksh https://webpack.js.org/api/node/
