### ISSUE TITLE
Automatically package all the CSS files under the settings are not set.

### ISSUE THREAD

**Issue by GarveySun** [webpack/extract-text-webpack-plugin#267]
I wrote a list to manually control the CSS of components of the package i want to pack.
```
var componentList=[
        "YdAlert",
        "HistoryList",
        "HistoryBox"
];

componentList.map(function(match){
    require('./components/'+match+'/'+match+'.css');
});
```
And  there are no ‘require()’ in  CSS files.

But webpack packged all style files include that are not in the list. 

`require('./components/'+match+'/'+match+'.css');`will cause extract-text-webpack-plugin pack all the files in the directory?

Thank you.

**Comment by Kovensky** [comment]
Webpack doesn't know that `match` can only have 3 values. It can be literally any string, including a string with `/`, so webpack includes everything.

You can use a `require.context` to specify a regexp for which files should be included, or `ContextReplacementPlugin` to do it in the config side.

**Comment by GarveySun** [comment]
I got it.
Thanks a lot
