### ISSUE TITLE
Problem with css modules

### ISSUE THREAD

**Issue by nasushkov** [webpack/extract-text-webpack-plugin#302]
I already posted this as a question on so, but I think it can be too specific, so I add an issue here. 
Right now I'm moving my current project from Webpack 1 to Webpack 2 and I encounter some problems with css modules which previously worked fine. In particular, I use css-loader and react-css-modules. My current development configuration is the following:

```
test: /module\.css$/,
use: [
        'style-loader',
        {
           loader: 'css-loader',
           options: {
              modules: true,
              importLoaders: 1,
              localIdentName: '[name]__[local]___[hash:base64:5]'
           }
        },
        'postcss-loader'
   ]
```

It works fine for Webpack 2. For production I use ExtractTextPlugin (version 2.0.0-beta.4) and my Webpack config for that case goes like this:

```
test: /module\.css$/,
loader: ExtractTextPlugin.extract({
          fallbackLoader: 'style-loader',
          loader: [
                    {
                       loader: 'css-loader',
                       options: {
                           modules: true,
                           importLoaders: 1,
                           localIdentName: '[hash:base64:5]'
                       }
                     },
                     'postcss-loader'
                    ]
                }),
```

In this case build fails with the following error:

>  Module build failed: Error: composition is only allowed
>  when selector is single :local class name

It seems like it doesn't prepend local prefixes. It is also mentioned in the css-loader documentation:

> Note: For prerendering with extract-text-webpack-plugin you should use css-loader/locals instead of style-loader!css-loader in the prerendering bundle. It doesn't embed CSS but only exports the identifier mappings.

So I tried loader: 'css-loader/locals' as well as adding it to options, but, unfortunately, nothing works

**Comment by andykenward** [comment]
try changing `options` to `query`. That fixed it for me
```
test: /module\.css$/,
loader: ExtractTextPlugin.extract({
          fallbackLoader: 'style-loader',
          loader: [
                    {
                       loader: 'css-loader',
                       query: {
                           modules: true,
                           importLoaders: 1,
                           localIdentName: '[hash:base64:5]'
                       }
                     },
                     'postcss-loader'
                    ]
                }),
```

**Comment by alferov** [comment]
@andykenward It worked out, thanks!

**Comment by davidcalhoun** [comment]
This is a really tough one to spot.  It really ought to be changed from `query` to `options` (see #281)
