### ISSUE TITLE
Why postcss stops working when used inside webpack's text extract plugin?

### ISSUE THREAD

**Issue by felixsanz** [webpack/extract-text-webpack-plugin#318]
Using webpack 2.

"extract-text-webpack-plugin": "2.0.0-beta.4",
"webpack": "2.2.0-rc.2",
"postcss-loader": "^1.1.1",

This loader works fine:

```javascript
{
  loader: 'postcss-loader',
  options: {
    plugins: () => [
      atImport({
        onImport() {
          console.log('--------------------------------------------------------')
        },
      }),
    ],
  },
},
```

And also having the plugins inside `postcss.config.js` works too.

But when I wrap `postcss-loader` inside `ExtractTextWebpackPlugin.extract()` it stops working.

I only get a bunch of:

```
Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @import "../../styles/config.css";
```

And I never see that console.log again. I'm 99% sure that the postcss config is not even read anymore.

Anyone had this troubles before?

CC @ai

**Comment by felixsanz** [comment]
Apparently this fixed it: https://github.com/iamdustan/webpack-2-extract-css-modules-repro/commit/adec7250b92f90b4117118458df206cfed283507

And this is related to #265 and many other issues. I hope it gets fixed soon because i just wasted 4 hours...

**Comment by sunny-g** [comment]
What worked for me specifically (with regards to what's in @felixsanz post):

1. using the `loader` key for the `ExtractTextPlugin.extract` loader
2. passing in an array into `extract`
3. using `query` instead of `options` within the `css-loader` definition
