### ISSUE TITLE
extract css failed

### ISSUE THREAD

**Issue by TNT-Likely** [webpack/extract-text-webpack-plugin#319]
<img width="536" alt="6d86f25a-6ab5-4229-a1ac-855a7a26dd9a" src="https://cloud.githubusercontent.com/assets/9278923/21517072/e51f8996-cd16-11e6-8b70-a3e1ef890ce4.png">
<img width="557" alt="0702035e-62c4-417c-803d-b12a71b190e1" src="https://cloud.githubusercontent.com/assets/9278923/21517093/02a69982-cd17-11e6-9946-30717e9c093e.png">

**Comment by TNT-Likely** [comment]
![qq20161228-0](https://cloud.githubusercontent.com/assets/9278923/21517118/3e2369f4-cd17-11e6-898f-3074ebeea0cc.png)

**Comment by MihaMarkic** [comment]
I think you are using a plugin built for webpack v1.x.

**Comment by pburtchaell** [comment]
You should not be using v1. Check the [releases](https://github.com/webpack/extract-text-webpack-plugin/releases) for the latest beta release.

**Comment by jcperez-ch** [comment]
@TNT-Likely you are using `webpack@2.1.0-beta.6` and `extract-text-webpack-plugin@1.x` these versions are incompatible, your bet is to get the correct version for `webpack@2.1.0-beta`

So 

```
npm i extract-text-webpack-plugin@2.0.0-beta.4
```

would be your fix for now.  If you see a different issue, then let us know.

**Comment by bebraw** [comment]
@TNT-Likely Any luck with the suggested solution?

**Comment by jcperez-ch** [comment]
I guess this can be closed...
