### ISSUE TITLE
styles.css request points to wrong path

### ISSUE THREAD

**Issue by MihaMarkic** [webpack/extract-text-webpack-plugin#320]
I have this odd issue.
I'm extracting styles.css and that's fine and mostly works, except when path gets too deep, more than one node deep.
i.e.
when requesti on http://localhost/ or http://localhost/node1 the request for styles.css is correct: http://localhost/styles.css.
But when request contains two nodes like https://localhost/node1/node2, the request for styles becomes: http://localhost/**node1/**styles.css for some reason.

Am I missing something obvious?

Using webpack 1.14, etp version 1.0.1 and reactjs.
Styles.css are imported in index.js as:
import './styles/styles.less';

Here is webpack.config excerpt: {test: /(\.less)$/, loader: ExtractTextPlugin.extract("style", "css-loader!less-loader", { publicPath: "/" })}, // publicPath doesn't help

**Comment by MihaMarkic** [comment]
I see that ETP? inserts a 
<link rel="stylesheet" href="styles.css"> into index.html. Even though the path should be "/styles.css".
Furthermore, if I configure ETP with dynamic name, i.e. new ExtractTextPlugin('css/[name]-[hash].css'), the href will still be "styles.css".

**Comment by MihaMarkic** [comment]
OK, that was some code in my build process that inserted the wrong Link.

**Comment by BenMGilman** [comment]
@MihaMarkic What exactly did you do to fix this? I'm running into the exact same issue

**Comment by BenMGilman** [comment]
...nevermind

**Comment by MihaMarkic** [comment]
@BenMGilman Actually I didn't solve it. I found that my script was generating that <link ... /> and simply removed it from the script. And since my CSS is very small I just use it embedded.
So if you know how to add hashed css reference I'm still interested.
