### ISSUE TITLE
update support webpack@2.2.0-rc.x version to npm

### ISSUE THREAD

**Issue by Justinidlerz** [webpack/extract-text-webpack-plugin#321]
update support webpack@2.2.0-rc.x version to npm

**Comment by pburtchaell** [comment]
There is an issue open for this at #309. I might suggest next time you open an issue on any project in GitHub that you search for existing issues first. It is not respectful to the time of the project maintainer(s) to create duplicate issues.

**Comment by Justinidlerz** [comment]
i'm so sorry
