### ISSUE TITLE
Further optimize the resulting asset?

### ISSUE THREAD

**Issue by philipp-spiess** [webpack/extract-text-webpack-plugin#331]
I'd like to further optimize one of the assets generated via `extract-text-webpack-plugin` (the CSS composition). What webpack hook can I use to make this? Do you know of any good writeup of how the current hooks work and under what circumstances they fire? 

In the official webpack documentation[1], I can't find  a clue about what hook would fit in this case. I tried `optimize-chunk-assets` but this was called more then a few times for what results in the same file so I guess this is before `extract-text-webpack-plugin` can create the proper combined asset.

---
[1] https://webpack.github.io/docs/plugins.html#the-compilation-instance

**Comment by bebraw** [comment]
Combination of `compiler.plugin('this-compilation', ...)` and `compilation.plugin('additional-assets', ...)` within that works. I use that idea for [purifying](https://github.com/webpack-contrib/purifycss-webpack-plugin).

It is important the plugin order is right (your plugin should go after extract-text-plugin).
