### ISSUE TITLE
Issues building styles with Bourbon, Neat, Sass loader

### ISSUE THREAD

**Issue by kingscott** [webpack/extract-text-webpack-plugin#333]
Hey all, running into some issues that have me a bit stumped. I have a small JS library that when compiled, exports a [compiled] minified JS file and a css file (compiled from sass). 

My webpack config looks like this:

```javascript
const path = require('path');
const bourbon = require('node-bourbon').includePaths;
const neat = require('node-neat').includePaths;
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const webpack = require('webpack');

module.exports = {
  devtool: 'source-map',
  entry: [
    './some/js/file.js',
    './styles/folder/styles.scss'
  ],
  output: {
    path: path.join(__dirname, '/dist/output'),
    filename: 'file.js',
    publicPath: '/'
  },
  plugins: [
    // Some plugins
    new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false
      }
    }),
    new ExtractTextPlugin('styles.css')
  ],
  module: {
    preLoaders: [
      { test: /\.json$/, exclude: /node_modules/, loader: 'json' }
    ],
    loaders: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'babel-loader',
        presets: ['es2015']
      },
      {
        test: /\.scss$/,
        loader: ExtractTextPlugin.extract('style', 'css?sourceMap!sass?sourceMap?outputStyle=compressed&includePaths[]=' + encodeURIComponent(bourbon) + '&includePaths[]=' + encodeURIComponent(neat[1]))
      }
    ]
  },
}
```

The above is being run with `NODE_ENV=production webpack -p --config webpack.production.config.js`. Seems pretty normal. 

But I'm getting an error: `Module build failed: BrowserslistError: Unknown version 55 of and_chr`. Been working on it for a few hours, but unable to make any new progress. Any idea what this error means and what the deal with it is? Thanks for any help!

Info:
*Node* version -> 6.2.2
*Webpack* version -> 1.14.0
*ExtractTextPlugin* -> 1.0.1
*OS* -> MacOS Sierra
*Language* -> JavaScript

**Comment by kingscott** [comment]
Solved this problem. Sorry!

**Comment by joshjg** [comment]
@kingscott May I ask how you solved it?

**Comment by kingscott** [comment]
Hey @joshjg, sure! I believe it was the way I defining the loader within `ExtractTextPlugin`. My config is more or less very similar, but the loader line for sass files looks like this:

```javascript
{
     ...
     loader: ExtractTextPlugin.extract([`css?sourceMap!sass?sourceMap?outputStyle=compressed&includePaths[]=${bourbon}&includePaths[]=${neat}]`
     ...
}
```

**Comment by mmahalwy** [comment]
I get the same problem when I add minimize to css-loader: `css-loader?minimize&...`

Any idea why?

**Comment by kingscott** [comment]
@mmahalwy With loaders in webpack, you don't need to write `css-loader`, you can just write `css?minimize...`. What does your entire loader string look like?

**Comment by mmahalwy** [comment]
@kingscott webpack 2 requires to be explicit. But I found the problem. It's due to caniuse-db being outdated. `npm install --save caniuse-db` solved it for me!

**Comment by kingscott** [comment]
Oh, interesting @mmahalwy! I was using webpack 1, unsure why they made the change back :-1: Glad you solved it!
