### ISSUE TITLE
css-loader options is not effect

### ISSUE THREAD

**Issue by likun7981** [webpack/extract-text-webpack-plugin#337]
```js
{
      loader: 'css-loader',
      options: {
        minimize: true,
        sourceMap: true
      }
}
```

webpack version : `2.2.0-rc.7`,
extract-text-webpack-plugin version: `2.0.0-beta.4`

css-loader `options` is not effect, must use `query`, like this:
```js
{
      loader: 'css-loader',
      query: {
        minimize: true,
        sourceMap: true
      }
}
```

**Comment by lvthanh101** [comment]
I tried options with **sass-loader** and it doesn't work too.

**Comment by malvadeza** [comment]
```
{
    loader: 'css-loader?sourceMap&minimize',
}
```

seems to work for me

**Comment by mrtnbroder** [comment]
Just noticed the same issue. I still need to use the deprecated `query` api to make things work.
Bump!

**Comment by jaydenseric** [comment]
Duplicates https://github.com/webpack/extract-text-webpack-plugin/issues/265 and https://github.com/webpack/extract-text-webpack-plugin/issues/281.

**Comment by bebraw** [comment]
Closing as a duplicate.
