### ISSUE TITLE
Plugin doesn't seem to work with hash or chunkhash.

### ISSUE THREAD

**Issue by brainkim** [webpack/extract-text-webpack-plugin#49]
If I extract css but don't also change any javascript chunks, webpack will output css files with the same hashed filename even if they've actually changed. Let me know if this is a wontfix or you need more information!

**Comment by sokra** [comment]
Try `[contenthash]` instead.

**Comment by brainkim** [comment]
I've moved away from using webpack to hash static files (using django instead), but I'll leave this open for now.

**Comment by bartkusa** [comment]
FYI, I can't repro this currently. I'm using [chunkhash] with Webpack 1.10.1.

I have a chunk w/ JS and CSS. I added `cursor: default;` to a CSS file, and did a build.

For the chunks that include that CSS file, the hash changed for the JS and the CSS files. Nothing changed in the JS files (except the URL to its source-map, which also includes the hash).

**Comment by SpaceK33z** [comment]
Closing, this seems to work fine now.
