### ISSUE TITLE
Module order isn't preserve between builds

### ISSUE THREAD

**Issue by bogdan-dumitru** [webpack/extract-text-webpack-plugin#52]
Hey there, I might be doing something wrong here but I noticed that every time I do a new build (without changing anything) the hash of my CSS is different and I can se chunks of the CSS shifting in order.

Given that CSS caching is one of the selling points outlined in the README, I think I'm doing something wrong, and I'm wondering if you guys have any insight/input on this. Cheers!

**Comment by sokra** [comment]
see https://github.com/webpack/webpack/issues/739

**Comment by bogdan-dumitru** [comment]
Thanks, good to know but I am already using the ``OccurenceOrderPlugin``, it keeps my JS entries an chunks in order but not the CSS, so I can't tell if I'm missing smth.

**Comment by natelaws** [comment]
I have the same problem when requiring multiple style sheets within the same .js file.  It seems as if the largest files end up as last in the extracted file.

I also use the OccurenceOrderPlugin.

**Comment by natelaws** [comment]
Threw together a repo which seems to illustrate the issue.  https://github.com/natelaws/extract-text-plugin-bug

**Comment by bogdan-dumitru** [comment]
awesome :+1: @natelaws I wanted to do this but I didn't find the time. I actually got to see red at the end in one build but it tends to favour the largest file like you mentioned. I wonder if it has something to do with how webpack optimises the dependency tree / orders the chunks... I've tried stepping through the code but I'm not getting really far. I'll try some more though. It's really annoying for us right now cose we migrated to using this in production and for every deploy the CSS always is built with a different hash even if nothing changed.

**Comment by steida** [comment]
I have opposite problem, After updating to 0.4, css is extracted in wrong order.

**Comment by sokra** [comment]
@steida working on that...

**Comment by natelaws** [comment]
So, I'm still seeing an issue here.  I just updated my test repo and now it seems to be including the files in alphabetical order and still not the order actually defined. 

Although it definitely looks like its consistent now :+1:

**Comment by Metallium** [comment]
facing the same issue: now dependencies are sorted alphabetically
using less-loader just to process @imports should not be the only fix :)

**Comment by adrianca** [comment]
Is there a fix or a workaround for this issue?

**Comment by steida** [comment]
It's closed and it works for me in github.com/este/este
