### ISSUE TITLE
Option to delete file where text has been extracted

### ISSUE THREAD

**Issue by timkelty** [webpack/extract-text-webpack-plugin#54]
I'm using to build my stylesheets: http://webpack.github.io/docs/stylesheets.html

I have 3 entrypoints: head (js), tail (js), and app (css).

Using this plugin, I end up with a `app.css`, but also a `app.js`, which I don't need.
Is there a built-in or recommended way to remove that file?

**Comment by sokra** [comment]
don't create a separate entry point for the style. add them to the head.

**Comment by timkelty** [comment]
I don't think I follow.
Ultimately, I want a .css file. Are you suggesting just not using `extract-text` and injecting the css via js?

**Comment by sokra** [comment]
> Are you suggesting just not using extract-text and injecting the css via js?

no, but the extraxt-text-plugin **extracts** the css from an existing js entry point. So you just put your css into the head entry point and the extract-text-plugin creates a separate css output file.

**Comment by timkelty** [comment]
@sokra I see, thanks!

**Comment by idiotstrike** [comment]
I'm interested in this too.

Is it possible to get away with using an entry point for the css files and somehow not generating the .js files? This is better for me as each of the .css files gets their own chunkhash. If I simply require() the .scss files in an entry point .js file, they get the same chunkhash as the .js files, which is not ideal.

Any ideas?

**Comment by tony** [comment]
This still feels like quantum physics to me, even with the benefit of https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/54#issuecomment-183778333

I need some situational awareness for this. How do you end up with just the .css file and no stray .js tag?

**Comment by timkelty** [comment]
@tony You would import/require your .css file within _an existing_ .js entry point, so there shouldn't be any "stray" js.

**Comment by tony** [comment]
Thanks @timkelty 

I fixed this, when using [django-webpack-loader](https://github.com/ezhome/django-webpack-loader) by switching

```html
{% render_bundle 'bulma' %}
```

to

```
{% render_bundle 'bulma' 'css' %}
```

**Comment by jamesopti** [comment]
@sokra I'm having the same need as this when using mini-css-extract-plugin with Webpack 4.

For various reasons, I need to compile and upload a separate `app.css` file.

Everything is working fine, but I'd love an option for mini-css-extract-plugin to delete the "empty" JS file it extracts the css from.

Ideas?
