### ISSUE TITLE
0.5.0 Still exhibits 0.4.0 bug

### ISSUE THREAD

**Issue by mtscout6** [webpack/extract-text-webpack-plugin#57]
I tried to update to 0.5.0 this morning in the [react-bootstrap](https://github.com/react-bootstrap/react-bootstrap) repo. You can see the problem when you run `npm run docs` there. With 0.3.8 the top nav bar has a dark background. With 0.4.0 and 0.5.0 it has a white background. I haven't dug into the root of the problem yet, but both those versions do not seem to work.

**Comment by deepsweet** [comment]
we have the same problem: `@0.3.8` is ok, `@0.4.0` and `@0.5.0` – wrong styles order.

**Comment by mistadikay** [comment]
same here. On `@0.3.8` the order is correct, `@0.4.0` and `@0.5.0` — messed up

**Comment by deakster** [comment]
Yea, I'm including a bunch of less files (all of them require'd in the same file, one after the other), and in the output CSS they are completely out of order.

**Comment by arnihermann** [comment]
Same here for me, I have the following in my code (plugin `@0.5.0`):

```
import 'normalize.css/normalize.css';
import 'nprogress/nprogress.css';
import 'globals.css';
import './index.css';
```

The output is ordered by `index.css`, then `globals.css`, `normalize.css` and last `ngprogress.css`.

**Comment by sokra** [comment]
``` css
/* in index.css */
@import 'normalize.css/normalize.css';
@import 'nprogress/nprogress.css';
@import 'globals.css';
```

**Comment by deepsweet** [comment]
still stucked with 0.3.8 and still can't figure out how to fix it from my side... :(

**Comment by mtscout6** [comment]
@sokra I presume you are thinking that @arnihermann's imports are in css, but ES6 uses the import keyword. In my case I'm using the babel-loader to parse my ES6 files, so using import should be fine entirely from js files.

**Comment by sokra** [comment]
> @sokra I presume you are thinking that @arnihermann's imports are in css, but ES6 uses the import keyword. In my case I'm using the babel-loader to parse my ES6 files, so using import should be fine entirely from js files.

I know, but you can fix it by importing it in css. `index.css` depends on that stuff and not `index.js`. extract-text-plugin (currently) only cares for ordering in css files, not for the exectution order inherited from js.

**Comment by mtscout6** [comment]
Is there any particular reason for the order not being maintained when multiple css files are imported via JavaScript? I would reasonably presume that JavaScript modules would be invoked in the order I specified, why not multiple CSS files after being extracted?

**Comment by deakster** [comment]
I am still having a ton of issues with this in 0.5.0 even after following the suggestion from @sokra. I refactored a bunch of my pages and components (js files) to only include a single stylesheet, which itself is responsible for including all other style dependencies in order. I am still getting ordering issues in every instance.

I can't spend any more time on this, but one thing I noticed is that even changing a small dependant style from ```a.css``` to ```a.less```, and updating it's associated ```@import "a.css";``` to ```@import "a.less";``` will change it's position in the output, while otherwise remaining the same. My project is a large mixture of plain css and less files, and I have to be able to mix and match them and include them deterministically.

The ordering works perfectly and as expected in 0.3.8, so looks like I will have to stick with that for now.

**Comment by sokra** [comment]
> The ordering works perfectly and as expected in 0.3.8, so looks like I will have to stick with that for now.

Yes, you can stick to that. I'll try to fix the ordering once I have some time available...

**Comment by necolas** [comment]
I think this bug is serious enough to make every version `>0.3.8` pretty much unusable for the intended purpose.

The cascade is different to what you get using just `style-loader!css-loader`. CSS order doesn't match order of JS imports.

For example, the extracted CSS is in the reverse order to the JS dependency chain. This writes the `View` CSS after `index.css`:

```js
import View from '../ui-View';
import './index.css';
```

And incremental compilations will change the order of the extracted CSS rules depending on which source CSS file was edited.

**Comment by antitoxic** [comment]
I was fighting this issue whole afternoon today. I wish I could help and provide a fix but I can't orient myself well in the source of the plugin, so I can only +1 this bug severity.

I widely use extract-text-plugin for webcomponent-like separation of styling - separate css files require()d in each component js file. Thus, I can't use the ordering in css workaround.

**Comment by sokra** [comment]
I hope it's fixed now... Can somebody verify it?

A neat side effect is that webpack now uses the order as default order, which should make bundle stable even without the OccurenceOrderPlugin...

**Comment by arnihermann** [comment]
@sokra I'm checking it out now.

**Comment by arnihermann** [comment]
@sokra Confirmed, works for me.

**Comment by AlexKVal** [comment]
Confirmed. It now works as it was in 0.3.8. :+1: 
Thank you :sparkle: :sparkles:

**Comment by necolas** [comment]
Resolved the issues we were experiencing too. Thanks!

**Comment by SimenB** [comment]
@sokra I don't know if it's this plugins fault, but I know get the wrong ordering in my css. All imports are in css, with just a single inport in the JS. `0.7.1` has the correct order, `0.8.0` has the wrong order

**Comment by sokra** [comment]
... :cry:

**Comment by mtscout6** [comment]
@sokra I agree this fixes my problem.

**Comment by deepsweet** [comment]
looks like my problem is gone too

**Comment by Metallium** [comment]
issue is still reproducible in 0.8.0

having

a.css
```css
.a{display:block}
```
b.css
```css
.b{display:block}
```
bundle.css
```css
@import url(b.css);
@import url(a.css);
```

0.3.8 result (correct)
```
.b{display:block}.a{display:block}
```
0.8.0 result (sorted alphabetically?)
```
.a{display:block}.b{display:block}
```

**Comment by necolas** [comment]
Using 0.8, I just experienced the issue where recompilation on-change resulted in the wrong css order. Must be a difficult problem to solve.

**Comment by TerenceZ** [comment]
This issue is still using 0.81.

**Comment by sokra** [comment]
another try to fix it... try webpack 1.11.0

**Comment by okonet** [comment]
It seems that this is broken again. I've tried both importing a CSS file via JS and CSS. Both ways result in a wrong order of inclusion.

* importing in CSS results in a proper order when CSS is extracted `disabled: false`
* importing in JS results in a wrong order when CSS is extracted `disabled: false`
* importing in CSS — wrong order when CSS extraction is disabled (in dev mode)
* importing in JS — right order when CSS extraction is disabled (in dev mode)

**Comment by zag2art** [comment]
WTF guys, the bugs go right into production! (:

**Comment by cage1618** [comment]
+1
I have the same issue!!!

**Comment by Denisrudov** [comment]
the same for me. wrong order 👎

**Comment by avnersorek** [comment]
+1

**Comment by MoLow** [comment]
+1

**Comment by 4kx** [comment]
+1

**Comment by zhangbg** [comment]
+1

**Comment by rodrigoelias** [comment]
+1
