### ISSUE TITLE
IE9 Selector Limits

### ISSUE THREAD

**Issue by mtscout6** [webpack/extract-text-webpack-plugin#59]
I have been using this plugin and it works really well on smaller sites. I'm running into a problem on a larger site where our commons bundle is getting more than 4095 rules. See [IEs statement of limitation](http://blogs.msdn.com/b/ieinternals/archive/2011/05/14/10164546.aspx)

My original goal with moving to this plugin was to support source maps of our styling to the less files that the styles came from. 

Prior to using webpack we were using Mimosa with our own Bless css plugin https://github.com/DarthFubuMVC/mimosa-bless. While [Bless](http://blesscss.com/) may eventually be a solution, it does not support source maps yet.

Is there a way to still have each of our root less files go to their own css file and still be attributed to the bundle they get associated with?

**Comment by sokra** [comment]
> My original goal with moving to this plugin was to support source maps of our styling to the less files that the styles came from.

The style-loader now also supports CSS SourceMaps.

---

There is not automatic thing for the IE selector limit (PR?) but you should be able to use multiple ETPs in your config and put some styles into the first and others into the second.

**Comment by mtscout6** [comment]
While source maps is one of my goals the other is to get all css to css files to parallelize the download of these assets.

I understand my original issue description states it's only for source maps, sorry about the confusion. I'd still prefer to figure out how to use this plugin in conjunction with another that I'm just getting started.

My colleague and I have forked bless since it really hasn't progressed for quite some time. You can see it at: https://github.com/css-band-aid/css-band-aid.

That took a little time and now we are coming back around to build a webpack plugin that uses css-band-aid to address this selector limit problem while still using this plugin.

I'm just now getting to the point about asking questions about this plugin and how it works since our new plugin will need to be applied after this one.

I've noted that you are attaching to the 'this-compilation' plugin, how does that differ from 'compilation'? Is it just a matter of ordering? I see both of them getting created with the same compilation object here: https://github.com/webpack/webpack/blob/6173bb83bad2b07e8f9f965f19f1b777c652b2fb/lib/Compiler.js#L360-L361

The new plugin I'm writing is the [band-aid-plugin](https://github.com/css-band-aid/band-aid-plugin) which is definitely in it's early stages still.

**Comment by mtscout6** [comment]
I'm not following what the `NormalModuleFactory` is, documentation on it is sparse: http://webpack.github.io/docs/plugins.html#normalmodulefactory

I'm trying to understand what this is doing: https://github.com/webpack/extract-text-webpack-plugin/blob/master/index.js#L98-L110

**Comment by mtscout6** [comment]
Answers to these questions are can be found on [gitter April 21 2015 11:13 AM](https://gitter.im/webpack/webpack?at=5536852dc6d9d4681f87e230)

**Comment by SpaceK33z** [comment]
Closing because this is outside the scope of this package and questions have been answered.
