### ISSUE TITLE
Duplicate code in output

### ISSUE THREAD

**Issue by kibin** [webpack/extract-text-webpack-plugin#60]
Say I have multiple components that require the same css file. When I use this plugin I get output file with multiple duplications of the contents of this file. Is there a way to prevent extracting files that were already extracted in the output file?

**Comment by zimok** [comment]
I'm experiencing this issue too.
Tried with DedupePlugin and UglifyJsPlugin, without success.

**Comment by zimok** [comment]
It seems that this is something that has to be handled by the specific loader.

See, for example:
https://github.com/jtangelder/sass-loader/issues/31

I'm facing this problem with cssnext-loader.

**Comment by kibin** [comment]
@zimok yeah, you’re right, the issue is happening before extract text plugin starts working

**Comment by phun-ky** [comment]
While the original issue here is related to sass/less/stylus, a fix/hack/patch for this is to use the `optimize-css-assets-webpack-plugin` in conjunction with `extract-text-webpack-plugin` to produce, like this: https://gist.github.com/phun-ky/766e5ec9f75eac61c945273a951f0c0b. 

If you want to use this in dev, you will have to use a plugin like `write-file-webpack-plugin` to force webpack to write the file to disk in dev.
