### ISSUE TITLE
CSS source maps no longer being output

### ISSUE THREAD

**Issue by jordansexton** [webpack/extract-text-webpack-plugin#61]
At some point, extract-text-webpack-plugin, style-loader, and/or css-loader stopped outputting CSS source maps.

I've created a repo to demonstrate: [css-source-map-test](jordansexton/css-source-map-test)

If you run the webpack config from the example directory of this project, or the zip from issue #24, you can see the same result.

Steps to test:
```
git clone https://github.com/jordansexton/css-source-map-test.git
cd css-source-map-test
npm install
webpack
```

Expected output:
```
index.js
index.css
index.js.map
index.css.map
```

Actual output: ([example gist](https://gist.github.com/babsonmatt/a3389329794142adf8f5))
```
index.js
index.css
index.js.map
```

I've verified this on three machines running node 0.12.2, iojs 1.6.4, and iojs 1.6.2. I believe CSS source maps were being output as of my testing last week, but something broke and I don't know what.

I've also tested this with css-loader 0.9.1 to check if recent changes broke it with no luck.

**Comment by sokra** [comment]
The `SourceMapDevToolPlugin` has a default `test` of `/\.js$/`... (We may need to change this)

As workaround you can add the `SourceMapDevToolPlugin` with `test: /\.css(\?|$)/`
http://webpack.github.io/docs/list-of-plugins.html#sourcemapdevtoolplugin

**Comment by jordansexton** [comment]
That worked, thanks!
