### ISSUE TITLE
css file never written

### ISSUE THREAD

**Issue by foresttoney** [webpack/extract-text-webpack-plugin#66]
I have been unable to get a css file output using the extract-text-webpack plugin. There are no errors being thrown however the `style.bundle.css` file is never created.

```
'use strict';

var ExtractTextPlugin = require("extract-text-webpack-plugin");
var webpack = require('webpack');

module.exports = {

  context: __dirname + '/src',

  devtool: 'source-map',

  entry: {
   app: './app',
   vendor: [
     'immutable',
     'react'
   ]
  },

  module: {
    loaders: [
      {
        loader: ExtractTextPlugin.extract('style', 'css!sass'),
        test: /\.scss$/,
      }, 
      {
        exclude: /node_modules/,
        loader: 'babel',
        test: /\.js$/
      }
    ]
  },

  output: {
    filename: __dirname +  '/dist/[name].bundle.js'
  },

  plugins: [
    new ExtractTextPlugin('style.bundle.css', {
      allChunks: true
    }),

    new webpack.optimize.CommonsChunkPlugin({
      filename: __dirname + '/dist/vendor.bundle.js',
      minChunks: Infinity,
      name: 'vendor'
    })
  ],

  stats: {
    colors: true,
    reasons: true
  }

};
```

**Comment by sokra** [comment]
Propably fixed. Could you try it with the lastest version?

**Comment by foresttoney** [comment]
I am still seeing this is `0.8.0`.

**Comment by sokra** [comment]
`output.path` is missing.

``` js
output: {
  path: __dirname +  '/dist',
  filename: '[name].bundle.js'
}
```

**Comment by foresttoney** [comment]
Sorry, I had previously included `output.path`. Prior to including it, the `.js` and `.js.map` files were being dumped into root. However, `style.bundle.css` was still not being created.

**Comment by ChrisC** [comment]
I am seeing this same issue in 0.8.2. Output file is not generated, even though there are no errors thrown.

**Comment by JordyVialoux** [comment]
Did you manage to find a fix for this? Currently having the same issue

**Comment by karoltarasiuk** [comment]
Also experiencing the same issue here. It gives me this output:
```
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 2.22 kB [rendered]
        [0] ./~/css-loader?sourceMap!./~/sass-loader?sourceMap!./sass/HelloWorld.scss 764 bytes {0} [built]
        [1] ./~/css-loader/lib/css-base.js 1.46 kB {0} [built]
```
All is green but file is never there...

**Comment by eltian** [comment]
I'm having the same issue, the file is never generated. `output.path` is there, no error messages, but the file is not generated.

**Comment by peterlawless** [comment]
I'm having the same issue, too.

**Comment by chasedeanda** [comment]
+1 same issue

**Comment by eltian** [comment]
Just a heads up: apparently, my problem was related to the fact that I was using webpack-dev-middleware to run a development server. running `webpack` on the shell and avoiding the dev server allowed webpack to generate the needed files.

**Comment by vldmr1986** [comment]
+1 same issue
I m using: 
webpack-dev-middleware
webpack-hot-middleware

**Comment by jy95** [comment]
Same for me, nothing

**Comment by abhinavsingi** [comment]
Same issue with webpack-2, not using dev server though

**Comment by kuanyen** [comment]
.........
Is this problem still has no solution...? Alas...

**Comment by evilebottnawi** [comment]
@here Please create new issue, don't write about own problems here, thanks!
