### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by tomatau** [webpack/extract-text-webpack-plugin#67]
I'm trying to get my favicon to be copied during webpack bundle.

Here's a section of my config:
```coffee
  entry:
    "main" : [
      FILES.entry,
      "#{CSS}/theme.less",
      "#{SRC}/favicon.ico"
    ]
# ...
  module:
    loaders: [{
      test: /\.ico$/,
      loader: ExtractTextPlugin.extract('file')
    }, {
      test: /\.less$/,
      loader: ExtractTextPlugin.extract('style', 'css!less')
# ...
    }]
# ...
  plugins: [
    new ExtractTextPlugin("style.[hash].css",
      allChunks: true
    ),
    new ExtractTextPlugin("favicon.ico",
      allChunks: false
    )
# ...
  ]
```

This creates a favicon file in my output folder, but it's not a valid ico so doesn't work. Am I using the plugin incorrectly? Should I be using a different loader? Have tried specifying a mimetype at the loader but it makes no difference.

**Comment by sokra** [comment]
Not related to the ExtractTextPlugin.

**Comment by tomatau** [comment]
Bit of feedback as to whether the config is correct would be nice? Not much documentation or examples for multiple extractions

**Comment by sokra** [comment]
The `ExtractTextPlugin` doesn't work this way. You cannot extract files...
