### ISSUE TITLE
Module not found: Error: Cannot resolve module 'ExtractTextPlugin.extract("style-loader", "css-loader")' 

### ISSUE THREAD

**Issue by yhjor1212** [webpack/extract-text-webpack-plugin#71]
Below is my config:

var ExtractTextPlugin = require("extract-text-webpack-plugin");

module.exports = {
  entry: './public/app.js',

  output: {
    path: require("path").resolve('./public/dist/'),
    filename: 'app.js'
  },

  resolve: {
  	modulesDirectories: ['node_modules'],
    extensions: ['', '.js', '.jsx'],
    alias: {
      'jquery': __dirname + '/public/assets/bower_components/jquery/dist/jquery.min.js'
    }
  },

  module: {
    loaders: [
      { test: /\.js[x]?$/, exclude: /node_modules/, loader: 'jsx-loader?insertPragma=React.DOM&harmony' },
      { test: /\.css$/, loader: 'ExtractTextPlugin.extract("style-loader", "css-loader")' },
      { test: /\.(png|jpg)$/, loader: 'file-loader?name=images/[name].[ext]' },
      { test: /\.woff.*$/, loader: 'file-loader?name=fonts/[name].[ext]' },
      { test: /\.ttf$/, loader: "url?limit=10000&minetype=application/octet-stream" },
      { test: /\.eot.*$/, loader: "file" },
      { test: /\.svg.*$/, loader: "url?limit=10000&minetype=image/svg+xml" }
    ]
  },

  externals: {
    'react': 'React',
    'jquery': 'jQuery'
  },

  plugins: [
      new ExtractTextPlugin("bundle.css")
  ]
}

How can I solve this?

**Comment by LeoLeBras** [comment]
Same problem, how do you fix that ?

**Comment by andreypopp** [comment]
`'ExtractTextPlugin.extract("style-loader", "css-loader")'` should be `ExtractTextPlugin.extract("style-loader", "css-loader")`. Note that's not a string, that's a JS expression, no need to put it inside `'` quotes.

**Comment by LeoLeBras** [comment]
Thanks, it's work ! :)
