### ISSUE TITLE
Order of CSS is wrong after incremental compilation

### ISSUE THREAD

**Issue by necolas** [webpack/extract-text-webpack-plugin#73]
CSS order is changed upon incremental recompilation triggered by a change to a CSS file. It no longer matches the order of the initial compilation.

Versions:

* `extract-text-webpack-plugin@0.8.1`
* `webpack@1.9.10`
* `webpack-dev-server@1.9.0`

For example:

```js
// MyComponent.js

import View from '../ui-View';
import './index.css';

// etc
```

Initial compilation produces:

```css
.View { ... }
.MyComponent { ... }
```

Saving a change to `index.css` triggers a rebuild and produces:

```css
.MyComponent { ... }
.View { ... }
```

**Comment by fubupc** [comment]
+1

Same problem here!

**Comment by vn38minhtran** [comment]
Same problem.

**Comment by jbpros** [comment]
Same issue here.

**Comment by sokra** [comment]
fixed by https://github.com/webpack/webpack/commit/e20c4859286843fbf37941541693e00f4ae66238
