### ISSUE TITLE
Getting error when use from webpack-dev-server node's api

### ISSUE THREAD

**Issue by let4be** [webpack/extract-text-webpack-plugin#82]
http://hastebin.com/igaponazaw.pl

https://github.com/webpack/extract-text-webpack-plugin/blob/master/index.js#L22

changing condition to
`if(!c || c.initial) return;`
seems to solve to problem

**Comment by erwingaitano** [comment]
I'm having the same issue. Every time webpack recompiles the second time I got the error:

 `Cannot read property 'initial' of undefined`

Due to `c` being undefined.

**Comment by RabidFX** [comment]
@erwingaitano This seems related to #115  indeed. Can you give a try to my fix? (Pull request [here](https://github.com/webpack/extract-text-webpack-plugin/pull/170)) I'll add some information to the PR if it solves your issue aswell.

**Comment by erwingaitano** [comment]
Thanks @RabidFX !
Your solution is indeed working.

**Comment by RabidFX** [comment]
@erwingaitano  Thank you for the information, I'll update the PR description accordingly.
