### ISSUE TITLE
Plugin hangs when used with UglifyJS plugin

### ISSUE THREAD

**Issue by jsg2021** [webpack/extract-text-webpack-plugin#86]
I can't seem to reopen the old issue #34 and the example project isn't available anymore. :/

**Comment by jsg2021** [comment]
I'm seeing this on:
webpack 1.10.1 
extract-text-webpack-plugin 0.8.2

I can work around it buy `-minimize` on my css loader.

**Comment by jsg2021** [comment]
I'm starting to think its actually a css-loader issue.

**Comment by GuilhermeMedeiros** [comment]
@jsg2021 did you get this fixed? I have a terrible performance when ExtractText plugin is enabled.

**Comment by jsg2021** [comment]
@GuilhermeMedeiros I forced CSS minification off and its fine now.

This is my loader config:

```es6
{ test: /\.(s?)css$/, loader: ExtractTextPlugin.extract(
	'style-loader',
	'css?sourceMap&-minimize!autoprefixer!resolve-url!sass?sourceMap'
	)
}
```

The key bit is the `-minimize`

**Comment by GuilhermeMedeiros** [comment]
It is still slow, even with -minimize. 
I don't know if it's trying to extract text from my `.png` images or something :s
