### ISSUE TITLE
Is the webpack peerDependency necessary?

### ISSUE THREAD

**Issue by af** [webpack/extract-text-webpack-plugin#90]
Currently this package has webpack listed in its `peerDependencies`, and I'm wondering if that's necessary or if it's possible to find an alternate way of codifying the dependency on webpack. 

The reason I ask is that I'm trying to write a webpack loader that "wraps" several other loaders, including this one. However, the peer dependency on webpack would require my loader to also include `webpack` as a dependency, even though any consuming project will already have it higher in its dependency tree.

Presumably the peer dep is there to show which version of webpack a given release is compatible with, which makes sense. And I'm also guessing my problem may be less of an issue when npm3 is out. In the meantime, is there any workaround (besides of removing the peer dep) for my case above?

**Comment by sokra** [comment]
you should include webpack as peerDependency in your thing.

**Comment by af** [comment]
That works! Thanks, didn't know peerDependencies looked across multiple levels like that.
