### ISSUE TITLE
remove all styles from js files

### ISSUE THREAD

**Issue by cirsteve** [webpack/extract-text-webpack-plugin#96]
I have a webpack app with several entry points and I am trying to load all styles externally, this is how im instantiating the plugin
```
      new ExtractTextPlugin("[name].css", {allChunks: true}),
```

 however there still seems to be some styles that are being generated from javascript which is causing issues with the page flashing unstyled elements and the order styles are being applied. Is there a way for all styles to be loaded via external css files?

**Comment by filipmares** [comment]
+1
